#!/usr/bin/python

import optparse
import os
import sys

parser = optparse.OptionParser(usage='%prog [options]')

(options, args) = parser.parse_args()

os.environ['DEBIAN_FRONTEND'] = 'noninteractive'

from jolicloud_restore_utility.restore_utility import do_restore

if os.getuid():
    os.system( 'sudo -E jolicloud-restore-utility' )
    sys.exit()

do_restore()
