#!/usr/bin/python

import optparse

parser = optparse.OptionParser(usage='%prog [options]')

(options, args) = parser.parse_args()

from jolicloud_restore_utility.restore_utility import do_restore

do_restore()
