#!/usr/bin/python

import optparse
import os

parser = optparse.OptionParser(usage='%prog [options]')

(options, args) = parser.parse_args()

os.environ['DEBIAN_FRONTEND'] = 'noninteractive'

from jolicloud_restore_utility.restore_utility import do_restore

do_restore()
