#!/bin/sh -e
cp /etc/sudoers /etc/sudoers.jolicloud_restore_utility
sed '/# JOLICLOUD-RESTORE-UTILITY-START/,/# JOLICLOUD-RESTORE-UTILITY-END/ d' < /etc/sudoers.jolicloud_restore_utility > /etc/sudoers
rm /etc/sudoers.jolicloud_restore_utility

exit 0
